// <auto-generated />
using System;
using LotteryAnalysisApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LotteryAnalysisApp.Migrations
{
    [DbContext(typeof(LotteryContext))]
    [Migration("20230727031746_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LotteryAnalysisApp.LotteryDraw", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DrawDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("LotteryDraws");
                });

            modelBuilder.Entity("LotteryAnalysisApp.WinningNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("LotteryDrawId")
                        .HasColumnType("int");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LotteryDrawId");

                    b.ToTable("WinningNumber");
                });

            modelBuilder.Entity("LotteryAnalysisApp.WinningNumber", b =>
                {
                    b.HasOne("LotteryAnalysisApp.LotteryDraw", "LotteryDraw")
                        .WithMany("WinningNumbers")
                        .HasForeignKey("LotteryDrawId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LotteryDraw");
                });

            modelBuilder.Entity("LotteryAnalysisApp.LotteryDraw", b =>
                {
                    b.Navigation("WinningNumbers");
                });
#pragma warning restore 612, 618
        }
    }
}
